---
apiVersion: v1
kind: Service
metadata:
  name: external-adaptive-pricing
  labels:
    app: external-adaptive-pricing
spec:
  type: NodePort
  selector:
    app: external-adaptive-pricing
  ports:
  - protocol: TCP
    port: 8050
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: external-adaptive-pricing
  name: external-adaptive-pricing
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: external-adaptive-pricing
  template:
    metadata:
      labels:
        app: external-adaptive-pricing
    spec:
      containers:
      - image: pit304/external-adaptive-pricing
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8050
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: external-adaptive-pricing
        ports:
        - containerPort: 8050