---
apiVersion: v1
kind: Service
metadata:
  name: featureflags-db
  labels:
    app: featureflags-db
spec:
  type: NodePort
  selector:
    app: featureflags-db
  ports:
  - protocol: TCP
    port: 5432
    name: jdbc-postgresql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: featureflags-db
  name: featureflags-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: featureflags-db
  template:
    metadata:
      labels:
        app: featureflags-db
    spec:
      containers:
      - image: pit304/featureflags-db
        name: featureflags-db
        ports:
        - containerPort: 5432